name: Deploy to staging
'on':
  push:
    branches:
      - main
jobs:
  redeploy_on_aws:
    runs-on: ubuntu-latest
    name: Deploy via SSH
    steps:
      uses: appleboy/ssh-action@v1.2.0
      with: null
      host: '${{ secrets.EC2_HOST }}'
      username: '${{ secrets.EC2_USER }}'
      key: '${{ secrets.EC2_SSH_KEY }}'
      script: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

        cd ~/minimal-portfolio

        git pull origin main

        pnpm install

        pnpm build

        pm2 restart dev_portfolio || pm2 start "pnpm start" --name dev_portfolio

        pm2 save
